---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
spec:
  encryptedData:
    password: AgCCt/zLgqF97tFuGP9S95xsiYl5/8KTScZ1MjMI5ztMIZK01nhNcqQzXaKb11kZnIbmsiLRk7DeXrntD+nfuxHJi1TNBV3j6EweAu1SXnx+BZ3iu5TtTmXQfwAQfrVuhko9IWEjt07qaWMKRlPxk1A0JqhnTCut9c9cqJmWMUpwCtThom5GpGA8Z1I0NA3vg80ad8VXri5DhiDJoaVpzLkUhn55uohkZDBDjlqbUjKoKrBoA9BZEeD7J2fMt3d/8JQidGwhug/gj1TWC2PiR7SdWHHTnC7EVQfTH49DU1Nn3z4ShPl6Zx1CQ5Rfjn1ug3F5dtraRrWP9Ws3XNnh6s6KdXxlL6E/R3d98t1hx38H0jbtprfpABldPoNGCiaX7IFM/s9ZaYoAaA8O1GSNCimTF6+us70pXKtbRFFfkbqnkPr5jfAVRLO/oiExOYsmmUvEm54iSlr5ls3IQ+ha99/1fvs5lVh72XNKmH98cPIB6L35p5A6Nz9q1sk/GoCog1WKHF65ugoX8Lzj9f1889OzWqB8INxhw5pz7waCDSq0gJLuG9oEv5i0s7iKPh3CYaODlxbEjTssiPhwgABD7aamAhndT16ocURy8cfczBfrm6JaevfRuoyL/ek4iK2Zj7h0DEccDTQF6fCzxJQMax6Zhj8CEB9OOy9c561Wd8Q5imTq/6tFvBih4Jh2oohFVT858G63pfHLHWx2
    username: AgCil2OPrX8l7jFpsaXDiQugAiW9PM7kb/sekZlpB59KTU7mOfqtyZANbGyG5K1NVFuUjsziZS0d3htJ6RC9IxkN6fzCmau2OCydxOmqTzFOTboj2MfE3GKiXFVZHL4cwA6QXQd1G97zmPBV3MHH+6kfO8IZXN9E0pilpZJDdS5nCtxhsq6f4As6pbX71OUU7mKgOsbbE4xF516IYmYWiZbLPswtQVKYpu2Eru2q2UuFK+zgHw2v7VXkBNBottEByym/F2+5lgqC4olpqqatk8vvfTOrrBsxcVHFJ2/J6RXtQipT2oDMF92ljW73dXHDniMp+56Itu4KxR7x0G48MauRcR4VDG5DXNe97UlEicxxdJ15WipdLN4pBHYY2VcB7cYzcX15fFV76/JfJBdW0XglEkxjeDkwlBLh5KTbE8o85HLpT4/sFpRFAKu9QqHoQgqLKuMKorpAfoELXclFTp/oXcKt6bdjrz9CHKQHD5yhUNaG44H+KHgRUO5UKYcDg8QYT8rV/S43qTx5INFiW3LKX/FYFhW+6Jvl6v0qmeanntlfSXL3FPl9nJut3ERCWwnyghNW32SvHcvdhJ+VJ/wt/xuMtJaKqJ5h/os7NOKgY/B5oOLizvLz8rtPc7ziaNZiUae/iI/TccEwPNWLuHwNvHDdKumZ1yILjmqNNfKJIBkBhYfmQo1xEM0//8Ra44ZwJZi9OqTr+x0=
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default
    type: Opaque
