apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: law1iet01/cicd-app:2.1.10
