apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    keel.sh/policy: "glob:*-staging"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: law1iet01/cicd-app:1.2.7-staging
