name: CI

on:
  push:
    tags:
      - '*'    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: sudo apt-get install -f yamllint shellcheck

    - name: Run shell check
      run: |
        pushd cicd/application
        make shellcheck
        popd

    - name: Run shell check
      run: |
        pushd cicd/application
        make yaml-lint
        popd

  build-image:
    runs-on: ubuntu-latest
    needs: test-k8s-minikube
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker login
      run: |
        docker login -u ${{ secrets.dockerUsername }} -p  ${{ secrets.dockerPassword}}
    - name: Build/Push image
      run: |
        pushd cicd/application
        make VERSION=${{ github.ref_name }} OTHER=${{ github.ref_name }} push-image
        popd
